### ISSUE TITLE
The people vs @jdonkervliet 1

### ISSUE THREAD

**Issue by MrHug** [pimotte/nomic#44]
I hereby charge @jdonkervliet with corrupting the game State by merging #12 which did not include a point update.

In accordance with rule 324 I am hereby the prosecutor in this Trial.

**Comment by MrHug** [comment]
I call forth @pimotte and @arthurbik for jury duty.

**Comment by jdonkervliet** [comment]
Sure.

**Comment by jdonkervliet** [comment]
I plead Guilty, and would like a punishment equal to the number of points suggested by the prosecutor.

**Comment by jdonkervliet** [comment]
The defense rests.

**Comment by MrHug** [comment]
I hold the defendant Guilty of this violation, but due to the nature of this offense I will not demand a point reduction. I only ask the jury to still award him the point he should have gotten for #12 thus restoring the game state. 

Unless the jury has questions, the prosecution requests a Verdict.

**Comment by pimotte** [comment]
I have no questions, and would be in favour of a Guilty verdict. Let's see what @arthurbik has to say.

**Comment by arthurbik** [comment]
I have no questions and do not believe there is a point to this trial, since the prosecutor and defendant want the same thing. Can I try to convince @pimotte that the defendant is Not-Guilty, thereby preventing him from getting a point?

I am in favour of a Guilty verdict. To restore the game state he should get a point.

**Comment by pimotte** [comment]
This case is completely clear to me. I see no room for misinterpretation of the facts.

The Jury rules a Guilty verdict, and consequently a 0 point reduction, since that is the only option that yields from the demands of prosecution and the defendants plea. I will merge Jesse's pull request to rectify the game state.

**Comment by MrHug** [comment]
![](http://i.imgur.com/XS5LK.gif)

**Comment by MrHug** [comment]
![](http://i.imgur.com/XS5LK.gif)
